### ISSUE TITLE
Add subset-based evaluation option

### ISSUE THREAD

**Issue by mdekstrand** [CCRI-POPROX/poprox-recommender#100]
Because full evaluation take so much time, we should add the ability to evaluate on subsets of the eval data, so there is an option to get evaluation results more quickly than the full eval time takes.

**Comment by karlhigley** [comment]
There's the MIND-small dataset, which might be the easiest thing to start with

**Comment by mdekstrand** [comment]
@karlhigley great idea, quickly spinning that up.
